---
- name: Create AWS Debian server and install Grafana with all dependencies
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: eu-north-1
    group: AWS_security_group
    vpc_subnet_id: subnet-xxxxxxxx
    inventory_file: /etc/ansible/inventories/inventory.ini
    key_name: AWS_key
    instance_type: t2.micro
    image: ami-0a91cd140a1fc148a
    grafana_port: 3000

  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        group: "{{ group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count: 1
        instance_tags:
          Name: grafana
      register: ec2_instance

    - name: Add new instance to inventory file
      lineinfile:
        dest: "{{ inventory_file }}"
        line: "{{ item.instances[0].public_dns_name }} ansible_user=ubuntu ansible_ssh_private_key_file=/etc/ansible/keys/ssh_key.pem"
        create: yes
      loop: "{{ ec2_instance.results }}"
      when: item.changed is defined

    - name: Update cache and install dependencies
      become: true
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - software-properties-common
        - gnupg2

    - name: Add Grafana GPG key
      become: true
      apt_key:
        url: https://packages.grafana.com/gpg.key

    - name: Add Grafana repository
      become: true
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install Grafana
      become: true
      apt:
        name: grafana
        update_cache: yes

    - name: Start Grafana service
      become: true
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Open port for Grafana
      become: true
      ufw:
        rule: allow
        port: "{{ grafana_port }}"
        proto: tcp

    - name: Show Grafana URL
      debug:
        msg: "Grafana is running at http://{{ ec2_instance.instances[0].public_dns_name }}:{{ grafana_port }}"
        
    - name: Add Prometheus GPG key
      become: true
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3EFE0E0A2F2F60AA
        state: present
   
    - name: Add Prometheus repository
      become: true
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: prometheus
   
    - name: Install Prometheus
      become: true
      apt:
        name: prometheus
        update_cache: yes
   
    - name: Start Prometheus service
      become: true
      service:
        name: prometheus
        state: started
        enabled: yes
