---
- name: Install Logstash and dependencies
  hosts: logstash_1
  become: true

  vars:
    logstash_version: "7.15.0"
    java_package: "openjdk-11-jre-headless"
    logstash_download_url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-amd64.deb"

  tasks:
  - name: Install required packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - gnupg2
        - software-properties-common

  - name: Add Elasticsearch GPG key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add Elasticsearch repository
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/{{ logstash_version }}/apt stable main
      state: present

  - name: Install Logstash
    apt:
      name: "{{ logstash_download_url }}"
      state: present

  - name: Install Java
    apt:
      name: "{{ java_package }}"
      state: present

  - name: Install required Logstash plugins
    command: "/usr/share/logstash/bin/logstash-plugin install {{ item }}"
    with_items:
      - logstash-input-beats
      - logstash-filter-grok
      - logstash-output-elasticsearch

  - name: Configure Logstash input
    lineinfile:
      path: /etc/logstash/conf.d/input.conf
      regexp: "^#?input {"
      line: "  beats { port => 5042 }"
      state: present
      backup: yes

  - name: Configure Logstash filter
    lineinfile:
      path: /etc/logstash/conf.d/filter.conf
      regexp: "^#?filter {"
      line: "  grok { match => { \"message\" => \"%{COMBINEDAPACHELOG}\" } }"
      state: present
      backup: yes

  - name: Configure Logstash output
    lineinfile:
      path: /etc/logstash/conf.d/output.conf
      regexp: "^#?output {"
      line: "  elasticsearch { hosts => [\"{{ hostvars[item]['ansible_host'] }}:9200\"] }"
    with_items: "{{ groups['elastic'] }}"

  - name: Start Logstash service
    systemd:
      name: logstash
      state: started
      enabled: yes